# Generated by Django 2.0 on 2017-12-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrematador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arrematador', models.CharField(max_length=100)),
                ('cpf_cnpj_arrematador', models.CharField(max_length=14)),
                ('rg_arrematador', models.CharField(max_length=50)),
                ('endereco_arrematador', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doador', models.CharField(max_length=100)),
                ('apelido_doador', models.CharField(max_length=100)),
                ('cpf_cnpj_doador', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
                ('url_image', models.ImageField(upload_to='arquivos/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField()),
                ('valor_arremate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('arrematador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arrematador')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=4)),
                ('doador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doador')),
                ('evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
                ('movimento_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Movimento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo_prenda_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoPrenda'),
        ),
    ]
