# Generated by Django 2.0 on 2017-12-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='grupo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels_core.GrupoEvento'),
        ),
    ]
