# Generated by Django 2.0 on 2017-12-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171221_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='movimento_fk',
        ),
        migrations.AddField(
            model_name='movimento',
            name='prenda_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Prenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenda',
            name='arrematada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='url_image',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
