# Generated by Django 2.0 on 2018-01-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171226_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrematador',
            name='cpf_cnpj_arrematador',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='arrematador',
            name='endereco_arrematador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='arrematador',
            name='rg_arrematador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
