# Generated by Django 2.0 on 2018-01-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180102_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrematador',
            name='nome_arrematador',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='data_movimento',
            field=models.DateField(auto_now=True),
        ),
    ]
