# Generated by Django 2.0 on 2018-01-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180102_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrematador',
            name='nome_arrematador',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
