# Generated by Django 2.0 on 2018-01-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180102_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprenda',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='tipos/imagens'),
        ),
    ]
