# Generated by Django 2.0 on 2018-01-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180103_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='prendas/imagens'),
        ),
        migrations.AddField(
            model_name='tipoprenda',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristicaprenda',
            unique_together={('prenda', 'caracteristica')},
        ),
    ]
