# Generated by Django 2.0 on 2018-01-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180103_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='valor_arremate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
