# Generated by Django 2.0 on 2018-01-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180104_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data_evento',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nome_evento',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='movimento',
            old_name='data_movimento',
            new_name='data_ocorrencia',
        ),
        migrations.RenameField(
            model_name='movimento',
            old_name='prenda_fk',
            new_name='prenda',
        ),
        migrations.RenameField(
            model_name='movimento',
            old_name='valor_arremate',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='prenda',
            old_name='evento_fk',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='prenda',
            old_name='tipo_prenda_fk',
            new_name='tipo_prenda',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='arrematador_fk',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='doador_fk',
        ),
        migrations.DeleteModel(
            name='Arrematador',
        ),
        migrations.DeleteModel(
            name='Doador',
        ),
        migrations.AddField(
            model_name='movimento',
            name='arrematador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Participante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenda',
            name='doador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Participante'),
            preserve_default=False,
        ),
    ]
