# Generated by Django 2.0 on 2018-01-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180108_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Prenda'),
        ),
    ]
