# Generated by Django 2.0 on 2018-01-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prenda_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Prenda'),
        ),
    ]
