# Generated by Django 2.0 on 2018-01-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180119_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='arrematada',
        ),
        migrations.AddField(
            model_name='prenda',
            name='arrematador',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrematador', to='core.Participante'),
        ),
    ]
