# Generated by Django 2.0 on 2018-01-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180125_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='grupo',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels_core.GrupoEvento'),
        ),
    ]
