# Generated by Django 2.0 on 2018-01-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180126_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Prenda', verbose_name='Doação de'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
