# Generated by Django 2.0 on 2017-12-21 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEvento',
            fields=[
                ('nome', models.TextField(max_length=30)),
                ('id', models.UUIDField(default=uuid.UUID('7d4e8c5b-d95e-4d2a-84a3-b2af609d2105'), editable=False, primary_key=True, serialize=False)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
    ]
