# Generated by Django 2.0 on 2017-12-21 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('channels_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoevento',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fddcc2a5-aeb2-4ab6-8790-2b75ce518da1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
