# Generated by Django 2.0 on 2018-01-02 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('channels_core', '0004_auto_20171226_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoevento',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57ffc6d7-ae2b-460b-ba14-9ba73ad5188c'), primary_key=True, serialize=False),
        ),
    ]
